### ISSUE TITLE
Probleme lors de la premiere connexion

### ISSUE THREAD

**Issue by Nyfero** [sdummett/ft_transcendence#1]
Pour reproduire :
* ./clear-docker
* docker-compose up --build
* (dans un autre terminal) docker exec -it nestjs.back sh
* npx prisma migrate dev
* se connecter via la page de login =>  {"statusCode":404,"message":"Image not found"}; La console affiche Failed to load resource: the server responded with a status of 404 (Not Found)
* Si on refresh error 500; si on reviens en arriere et que l'on se reconnecte ca passe

**Comment by sdummett** [comment]
The commit `c50f424b49e304a818a0bd50246704793cbd11f0` fix it.
